# Generated by Django 5.1.4 on 2025-01-31 02:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tv_programs', '0002_tvchannel_priority_tvprogram_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tvprogram',
            name='date',
            field=models.DateTimeField(unique=True),
        ),
        migrations.AlterField(
            model_name='tvprogram',
            name='tv_channel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tv_programs.tvchannel', verbose_name='Телеканал'),
        ),
    ]
